name: Chatops
on:
  issue_comment:
    types: [created]

jobs:
  command-dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/deploy') || startsWith(github.event.comment.body, '/swap')
    steps:
    - name: Generate token
      id: chatops_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.CHATOPS_APP_ID }}
        private_key: ${{ secrets.CHATOPS_APP_PRIVATE_KEY }}
    - name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v2
      with:
        commands: deploy, swap
        permission: admin
        issue-type: pull-request
        token: ${{ steps.chatops_token.outputs.token }}
        reaction-token: ${{ steps.chatops_token.outputs.token }}
